id: https://github.com/rootreal/linkml/config-schema
name: linkml-config-schema
title: LinkML Service Configuration Schema
description: Schema for validating LinkML service configuration files
version: 1.0.0
license: CC-BY-NC-4.0

prefixes:
  linkml: https://w3id.org/linkml/
  config: https://github.com/rootreal/linkml/config/

default_prefix: config
default_range: string

classes:
  LinkMLConfig:
    description: Complete LinkML service configuration
    attributes:
      typedb:
        description: TypeDB configuration settings
        range: TypeDBConfig
        required: true
      parser:
        description: Parser configuration settings
        range: ParserConfig
        required: true
      validator:
        description: Validator configuration settings
        range: ValidatorConfig
        required: true
      generator:
        description: Generator configuration settings
        range: GeneratorConfig
        required: true
      cache:
        description: Cache configuration settings
        range: CacheConfig
        required: true
      performance:
        description: Performance configuration settings
        range: PerformanceConfig
        required: true
      security_limits:
        description: Security limit settings
        range: SecurityLimits
        required: true
      network:
        description: Network configuration settings
        range: NetworkConfig
        required: true
      expression:
        description: Expression engine configuration
        range: ExpressionConfig
        required: true
      pattern_validator:
        description: Pattern validator configuration
        range: PatternValidatorConfig
        required: true
      multi_layer_cache:
        description: Multi-layer cache configuration
        range: MultiLayerCacheConfig
        required: true
      background_services:
        description: Background services configuration
        range: BackgroundServicesConfig
        required: true
      cli:
        description: CLI configuration settings
        range: CliConfig
        required: true

  TypeDBConfig:
    description: TypeDB connection and operation configuration
    attributes:
      server_address:
        description: TypeDB server address (host:port)
        range: string
        required: true
        pattern: "^[^:]+:[0-9]+$"
      default_database:
        description: Default database name
        range: string
        required: true
        pattern: "^[a-zA-Z][a-zA-Z0-9_-]*$"
      batch_size:
        description: Batch size for bulk operations
        range: integer
        required: true
        minimum_value: 1
        maximum_value: 10000
      connection_timeout_ms:
        description: Connection timeout in milliseconds
        range: integer
        required: true
        minimum_value: 1000
        maximum_value: 300000
      query_timeout_ms:
        description: Query timeout in milliseconds
        range: integer
        required: true
        minimum_value: 1000
        maximum_value: 300000
      max_retries:
        description: Maximum number of connection retries
        range: integer
        required: true
        minimum_value: 0
        maximum_value: 10
      retry_delay_ms:
        description: Delay between retries in milliseconds
        range: integer
        required: true
        minimum_value: 100
        maximum_value: 60000
      pool_size:
        description: Connection pool size
        range: integer
        required: true
        minimum_value: 1
        maximum_value: 100
      include_inferred:
        description: Include inferred facts in query results
        range: boolean
        required: true

  ParserConfig:
    description: Schema parser configuration
    attributes:
      max_recursion_depth:
        description: Maximum recursion depth for nested schemas
        range: integer
        required: true
        minimum_value: 10
        maximum_value: 1000
      enable_cache:
        description: Enable parser result caching
        range: boolean
        required: true
      cache_ttl_seconds:
        description: Parser cache TTL in seconds
        range: integer
        required: true
        minimum_value: 60
        maximum_value: 86400
      max_file_size_bytes:
        description: Maximum file size to parse in bytes
        range: integer
        required: true
        minimum_value: 1024
        maximum_value: 1073741824  # 1GB
      supported_formats:
        description: List of supported file formats
        range: string
        multivalued: true
        required: true
      max_import_depth:
        description: Maximum import depth for schema imports
        range: integer
        required: true
        minimum_value: 1
        maximum_value: 50

  ValidatorConfig:
    description: Validator configuration
    attributes:
      enable_parallel:
        description: Enable parallel validation
        range: boolean
        required: true
      thread_count:
        description: Number of validation threads
        range: integer
        required: true
        minimum_value: 1
        maximum_value: 64
      batch_size:
        description: Validation batch size
        range: integer
        required: true
        minimum_value: 1
        maximum_value: 10000
      timeout_ms:
        description: Validation timeout in milliseconds
        range: integer
        required: true
        minimum_value: 1000
        maximum_value: 3600000
      max_errors:
        description: Maximum errors before stopping
        range: integer
        required: true
        minimum_value: 1
        maximum_value: 100000
      fail_fast:
        description: Stop on first validation error
        range: boolean
        required: true
      compiled_cache_size:
        description: Size of compiled validator cache
        range: integer
        required: true
        minimum_value: 10
        maximum_value: 10000

  GeneratorConfig:
    description: Code generator configuration
    attributes:
      output_directory:
        description: Default output directory for generated code
        range: string
        required: true
      enable_formatting:
        description: Enable code formatting in output
        range: boolean
        required: true
      include_docs:
        description: Include documentation in generated code
        range: boolean
        required: true
      generator_options:
        description: Generator-specific options
        range: GeneratorOptions
        multivalued: true

  GeneratorOptions:
    description: Options for specific code generators
    attributes:
      template_path:
        description: Path to custom template
        range: string
      settings:
        description: Generator-specific settings
        range: string
        multivalued: true

  CacheConfig:
    description: Cache configuration
    attributes:
      max_entries:
        description: Maximum cache entries
        range: integer
        required: true
        minimum_value: 100
        maximum_value: 10000000
      ttl_seconds:
        description: Default TTL in seconds
        range: integer
        required: true
        minimum_value: 60
        maximum_value: 86400
      enable_compression:
        description: Enable cache compression
        range: boolean
        required: true
      eviction_policy:
        description: Cache eviction policy
        range: EvictionPolicy
        required: true
      expression_cache:
        description: Expression cache settings
        range: CacheSettings
        required: true
      rule_cache:
        description: Rule cache settings
        range: CacheSettings
        required: true

  CacheSettings:
    description: Specific cache component settings
    attributes:
      max_entries:
        description: Maximum entries for this cache
        range: integer
        required: true
        minimum_value: 10
        maximum_value: 1000000
      ttl_seconds:
        description: TTL for this cache in seconds
        range: integer
        required: true
        minimum_value: 60
        maximum_value: 86400

  PerformanceConfig:
    description: Performance tuning configuration
    attributes:
      enable_monitoring:
        description: Enable performance monitoring
        range: boolean
        required: true
      memory_limit_bytes:
        description: Memory limit in bytes
        range: integer
        required: true
        minimum_value: 104857600  # 100MB
        maximum_value: 137438953472  # 128GB
      cpu_limit_percent:
        description: CPU limit as percentage
        range: integer
        required: true
        minimum_value: 10
        maximum_value: 100
      enable_string_interning:
        description: Enable string interning optimization
        range: boolean
        required: true
      string_pool_size:
        description: String pool size
        range: integer
        required: true
        minimum_value: 1000
        maximum_value: 1000000
      enable_background_tasks:
        description: Enable background optimization tasks
        range: boolean
        required: true
      enable_cache_warming:
        description: Enable cache warming on startup
        range: boolean
        required: true
      background_task_interval_secs:
        description: Background task interval in seconds
        range: integer
        required: true
        minimum_value: 10
        maximum_value: 3600
      string_cache:
        description: String cache configuration
        range: StringCacheConfig
        required: true
      memory_pool:
        description: Memory pool configuration
        range: MemoryPoolConfig
        required: true
      cache_ttl_levels:
        description: Multi-level cache TTL settings
        range: CacheTtlLevels
        required: true

  StringCacheConfig:
    description: String cache configuration
    attributes:
      max_entries:
        description: Maximum cached strings
        range: integer
        required: true
        minimum_value: 100
        maximum_value: 1000000
      max_string_length:
        description: Maximum string length to cache
        range: integer
        required: true
        minimum_value: 10
        maximum_value: 65536

  MemoryPoolConfig:
    description: Memory pool configuration
    attributes:
      max_size_bytes:
        description: Maximum pool size in bytes
        range: integer
        required: true
        minimum_value: 1048576  # 1MB
        maximum_value: 10737418240  # 10GB
      chunk_size_bytes:
        description: Memory chunk size in bytes
        range: integer
        required: true
        minimum_value: 1024
        maximum_value: 1048576

  CacheTtlLevels:
    description: Multi-level cache TTL configuration
    attributes:
      l1_seconds:
        description: Level 1 cache TTL in seconds
        range: integer
        required: true
        minimum_value: 60
        maximum_value: 3600
      l2_seconds:
        description: Level 2 cache TTL in seconds
        range: integer
        required: true
        minimum_value: 300
        maximum_value: 14400
      l3_seconds:
        description: Level 3 cache TTL in seconds
        range: integer
        required: true
        minimum_value: 600
        maximum_value: 86400
      min_ttl_seconds:
        description: Minimum TTL in seconds
        range: integer
        required: true
        minimum_value: 10
        maximum_value: 3600
      max_ttl_seconds:
        description: Maximum TTL in seconds
        range: integer
        required: true
        minimum_value: 3600
        maximum_value: 604800

  SecurityLimits:
    description: Security limit configuration
    attributes:
      max_string_length:
        description: Maximum string length
        range: integer
        required: true
        minimum_value: 1000
        maximum_value: 10485760
      max_expression_depth:
        description: Maximum expression nesting depth
        range: integer
        required: true
        minimum_value: 10
        maximum_value: 1000
      max_constraint_count:
        description: Maximum constraints per validation
        range: integer
        required: true
        minimum_value: 100
        maximum_value: 100000
      max_cache_entries:
        description: Maximum total cache entries
        range: integer
        required: true
        minimum_value: 1000
        maximum_value: 10000000
      max_function_args:
        description: Maximum function arguments
        range: integer
        required: true
        minimum_value: 5
        maximum_value: 100
      max_identifier_length:
        description: Maximum identifier length
        range: integer
        required: true
        minimum_value: 50
        maximum_value: 1000
      max_json_size_bytes:
        description: Maximum JSON payload size
        range: integer
        required: true
        minimum_value: 1024
        maximum_value: 1073741824
      max_slots_per_class:
        description: Maximum slots per class
        range: integer
        required: true
        minimum_value: 100
        maximum_value: 10000
      max_classes_per_schema:
        description: Maximum classes per schema
        range: integer
        required: true
        minimum_value: 100
        maximum_value: 100000
      max_validation_time_ms:
        description: Maximum validation time in milliseconds
        range: integer
        required: true
        minimum_value: 1000
        maximum_value: 3600000
      max_memory_usage_bytes:
        description: Maximum memory usage in bytes
        range: integer
        required: true
        minimum_value: 104857600
        maximum_value: 137438953472
      max_parallel_validators:
        description: Maximum parallel validators
        range: integer
        required: true
        minimum_value: 1
        maximum_value: 1000
      max_cache_memory_bytes:
        description: Maximum cache memory in bytes
        range: integer
        required: true
        minimum_value: 10485760
        maximum_value: 10737418240
      max_expression_time_ms:
        description: Maximum expression evaluation time
        range: integer
        required: true
        minimum_value: 100
        maximum_value: 60000
      max_validation_errors:
        description: Maximum validation errors to collect
        range: integer
        required: true
        minimum_value: 100
        maximum_value: 100000

  NetworkConfig:
    description: Network configuration
    attributes:
      default_host:
        description: Default bind host
        range: string
        required: true
        pattern: "^[0-9]{1,3}\\.[0-9]{1,3}\\.[0-9]{1,3}\\.[0-9]{1,3}$|^localhost$|^[a-zA-Z0-9.-]+$"
      default_port:
        description: Default port number
        range: integer
        required: true
        minimum_value: 1024
        maximum_value: 65535
      api_timeout_seconds:
        description: API timeout in seconds
        range: integer
        required: true
        minimum_value: 1
        maximum_value: 300

  ExpressionConfig:
    description: Expression engine configuration
    attributes:
      enable_cache:
        description: Enable expression caching
        range: boolean
        required: true
      enable_compilation:
        description: Enable expression compilation
        range: boolean
        required: true
      cache_size:
        description: Expression cache size
        range: integer
        required: true
        minimum_value: 100
        maximum_value: 100000
      timeout_seconds:
        description: Expression timeout in seconds
        range: integer
        required: true
        minimum_value: 1
        maximum_value: 60
      max_recursion_depth:
        description: Maximum recursion depth
        range: integer
        required: true
        minimum_value: 10
        maximum_value: 1000

  PatternValidatorConfig:
    description: Pattern validator configuration
    attributes:
      default_cache_size:
        description: Default pattern cache size
        range: integer
        required: true
        minimum_value: 10
        maximum_value: 10000

  MultiLayerCacheConfig:
    description: Multi-layer cache configuration
    attributes:
      l3_max_size_bytes:
        description: L3 cache maximum size in bytes
        range: integer
        required: true
        minimum_value: 104857600
        maximum_value: 107374182400

  BackgroundServicesConfig:
    description: Background services configuration
    attributes:
      cache_ttl_check_interval_secs:
        description: Cache TTL check interval in seconds
        range: integer
        required: true
        minimum_value: 60
        maximum_value: 3600
      memory_cleanup_interval_secs:
        description: Memory cleanup interval in seconds
        range: integer
        required: true
        minimum_value: 60
        maximum_value: 7200
      panic_recovery_timeout_secs:
        description: Panic recovery timeout in seconds
        range: integer
        required: true
        minimum_value: 1
        maximum_value: 60
      error_recovery_timeout_secs:
        description: Error recovery timeout in seconds
        range: integer
        required: true
        minimum_value: 10
        maximum_value: 600

  CliConfig:
    description: CLI configuration
    attributes:
      default_iterations:
        description: Default iterations for performance tests
        range: integer
        required: true
        minimum_value: 1
        maximum_value: 1000000
      progress_bar_template:
        description: Progress bar template string
        range: string
        required: true
      progress_bar_finish_template:
        description: Progress bar finish template
        range: string
        required: true

enums:
  EvictionPolicy:
    description: Cache eviction policies
    permissible_values:
      Lru:
        description: Least Recently Used
      Lfu:
        description: Least Frequently Used
      Fifo:
        description: First In First Out
      Random:
        description: Random eviction
